### ISSUE TITLE
Более лучший шрифт для главного меню.

### ISSUE THREAD

**Issue by ivanproff** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#3]
Вот [этот](https://drive.google.com/open?id=14YnduKolEgcFVyuf27gzjbIvFGNNH6UR) лучше.

![20200215230218_1](https://user-images.githubusercontent.com/19212996/74594436-7ee41b80-5047-11ea-94b0-eb574983a94a.jpg)

**Comment by HellbringerOnline** [comment]
@ivanproff С каким из шрифтов вы тестировали? Только недавно была добавлена обновленная версия. Прикрепите картинку со скриншотом на котором шрифте из моего репозитория вы тестировали?

**Comment by ivanproff** [comment]
![1](https://user-images.githubusercontent.com/19212996/74609236-400e9e00-50f9-11ea-83a7-a6eca134db90.png)
![2](https://user-images.githubusercontent.com/19212996/74609242-4bfa6000-50f9-11ea-9cc0-43e5bd9c46fb.png)

**Comment by HellbringerOnline** [comment]
Шрифт может по ширине и больше подходит, но по начертанию букв больше подходить оригинальный.

**Comment by Polymega** [comment]
Also note: I removed the "glow" behind the words for all menu files outside of English, because the glow is only sized for the English options.

For example: The word "LOAD" is shorter than "ЗАГРУЗИТЬ". But the glow is sized to fit the width of "LOAD", therefore, the glow will not extend past the "ЗАГРУЗИТЬ" lettering the same as it does for "LOAD."

Because of this, it is easier to remove the glow for all non-English main menu files.
