### ISSUE TITLE
проблема с буквой "ш"

### ISSUE THREAD

**Issue by 60d74** [HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus#8]
похоже что в русификаторе от ZoG, во всех словах начинающихся на "ш", первая буква пропущена

а также предупреждение перед началом DLC (где типо "рекомендуется пройти основную кампанию перед началом") съезжает во всех версиях (во всех по разному)

из версии металлиста:
![sh2pc_2023_04_12_14_05_27_786](https://user-images.githubusercontent.com/125860266/231347117-21e2b8ce-c637-4e3b-adc3-65a5d9fdb928.png)

**Comment by 60d74** [comment]
и еще, совсем мелочь, но в новых версиях ee добавили поддержку японского, и с твоим паком он не работает (видимо нет шрифта)

**Comment by HellbringerOnline** [comment]
> а также предупреждение перед началом DLC (где типо "рекомендуется пройти основную кампанию перед началом") съезжает во всех версиях (во всех по разному)
> 
> из версии металлиста: ![sh2pc_2023_04_12_14_05_27_786](https://user-images.githubusercontent.com/125860266/231347117-21e2b8ce-c637-4e3b-adc3-65a5d9fdb928.png)

не совсем понял что именно съезжает.

**Comment by HellbringerOnline** [comment]
> похоже что в русификаторе от ZoG, во всех словах начинающихся на "ш", первая буква пропущена

без скринов будет проблемно найти хоть что-то

**Comment by HellbringerOnline** [comment]
> и еще, совсем мелочь, но в новых версиях ee добавили поддержку японского, и с твоим паком он не работает (видимо нет шрифта)

тоже нужен скрин что именно не работает

**Comment by mikeoxmaull** [comment]
> > и еще, совсем мелочь, но в новых версиях ee добавили поддержку японского, и с твоим паком он не работает (видимо нет шрифта)
> 
> тоже нужен скрин что именно не работает

![sh2pc_2023_04_14_23_00_27_081](https://user-images.githubusercontent.com/125860266/232051316-1156bacc-aeb6-4360-8956-49693e442914.png)
![sh2pc_2023_04_14_23_00_49_562](https://user-images.githubusercontent.com/125860266/232051335-d2398cec-1a62-4e89-a56d-66310926c94a.png)

**Comment by mikeoxmaull** [comment]
> > а также предупреждение перед началом DLC (где типо "рекомендуется пройти основную кампанию перед началом") съезжает во всех версиях (во всех по разному)
> > из версии металлиста: ![sh2pc_2023_04_12_14_05_27_786](https://user-images.githubusercontent.com/125860266/231347117-21e2b8ce-c637-4e3b-adc3-65a5d9fdb928.png)
> 
> не совсем понял что именно съезжает.

ну тут ясно видно, что так быть не должно

вот как в оригинале:
![sh2pc_2023_04_14_23_01_48_968](https://user-images.githubusercontent.com/125860266/232051511-e3e4b829-c74e-4be4-9224-fcaae44316e5.png)

вот как, например, у ashigaru
![sh2pc_2023_04_14_23_02_35_550](https://user-images.githubusercontent.com/125860266/232051667-80434b14-c956-4520-ac02-5dd9ab45cb62.png)

**Comment by 60d74** [comment]
> > похоже что в русификаторе от ZoG, во всех словах начинающихся на "ш", первая буква пропущена
> 
> без скринов будет проблемно найти хоть что-то

вот тут проблема, тк я уже достаточно прошел


> > а также предупреждение перед началом DLC (где типо "рекомендуется пройти основную кампанию перед началом") съезжает во всех версиях (во всех по разному)
> > из версии металлиста: ![sh2pc_2023_04_12_14_05_27_786](https://user-images.githubusercontent.com/125860266/231347117-21e2b8ce-c637-4e3b-adc3-65a5d9fdb928.png)
> 
> не совсем понял что именно съезжает.

ну тут ясно видно, что так быть не должно

вот как в оригинале:
![sh2pc_2023_04_14_23_01_48_968](https://user-images.githubusercontent.com/125860266/232051511-e3e4b829-c74e-4be4-9224-fcaae44316e5.png)

вот как, например, у ashigaru
![sh2pc_2023_04_14_23_02_35_550](https://user-images.githubusercontent.com/125860266/232051667-80434b14-c956-4520-ac02-5dd9ab45cb62.png)


> > и еще, совсем мелочь, но в новых версиях ee добавили поддержку японского, и с твоим паком он не работает (видимо нет шрифта)
> 
> тоже нужен скрин что именно не работает

перевод:
![sh2pc_2023_04_14_23_00_27_081](https://user-images.githubusercontent.com/125860266/232051316-1156bacc-aeb6-4360-8956-49693e442914.png)
![sh2pc_2023_04_14_23_00_49_562](https://user-images.githubusercontent.com/125860266/232051335-d2398cec-1a62-4e89-a56d-66310926c94a.png)

оригинал:
![sh2pc_2023_04_14_23_08_27_600](https://user-images.githubusercontent.com/125860266/232052659-2e0404a3-3a65-4891-8bb8-81e8c991222a.png)
![sh2pc_2023_04_14_23_08_40_550](https://user-images.githubusercontent.com/125860266/232052681-579c7784-03c0-4f5c-a2fb-98c4fd1432fd.png)

**Comment by HellbringerOnline** [comment]
@Polymega Hello, could you give some advice about this problem? I don't have Japanese characters in my translation. And my warning text has shifted when starting a new game from the DLC.
Perhaps in the new version you updated the TGA file with fonts?

**Comment by Polymega** [comment]
Hey Hellbringer,

A few questions:

1. Which language does the Russian translation pack replace? 
2. Where are you telling people to place your translation pack files? In the `data` folder, `sh2e` folder, or `lang` folder?

**Comment by HellbringerOnline** [comment]
> Hey Hellbringer,
> 
> A few questions:
> 
> 1. Which language does the Russian translation pack replace?
> 2. Where are you telling people to place your translation pack files? In the `data` folder, `sh2e` folder, or `lang` folder?

This pack replaces the English language, i say copy lang\ folder and language.ini file to game root folder

**Comment by Polymega** [comment]
Can you send me the Russian pack here so I can take a look?

**Comment by HellbringerOnline** [comment]
> Can you send me the Russian pack here so I can take a look?

You can grab the repository, it contains 4 variants of the Russian language pack https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus

**Comment by Polymega** [comment]
Thanks.

The Japanese language will _not_ work because you are using a modified font sheet to support Russian characters. Here is the original font sheet:

![font000](https://user-images.githubusercontent.com/27395260/232507694-f8099dd9-e19f-45a5-a2ea-c7b10ac7f265.jpg)

Here is the Russian font sheet:

![font000small](https://user-images.githubusercontent.com/27395260/232507725-53046761-e47f-48ac-b100-2cb1f3017760.jpg)

^ Typically, modified language pack font sheets chop off the Japanese characters to save on file size/performance. We actually warn about this on our project site for language packs that used modified font sheets:

![image](https://user-images.githubusercontent.com/27395260/232507064-2b747252-9bf6-408b-9c53-b7816306758c.png)

-------------------------

All Russian packs look to display this incorrectly:

![Screenshot 2023-04-17 09-52-44](https://user-images.githubusercontent.com/27395260/232505290-4e32f212-e3ac-40b5-84c8-dec9dbcb067f.png)
![Screenshot 2023-04-17 09-51-03](https://user-images.githubusercontent.com/27395260/232505275-53de9d0c-c6f0-4a8d-a4c0-e55593e1e343.png)
![Screenshot 2023-04-17 09-51-52](https://user-images.githubusercontent.com/27395260/232505277-3f804fce-c992-4ce1-b37c-1a546ae9c81a.png)
![Screenshot 2023-04-17 09-52-19](https://user-images.githubusercontent.com/27395260/232505283-eabe0ca6-1b4f-4f5a-946d-d7ac02a7fe37.png)

The way the game displays this portion of text is dumb/weird. I recommend using the [SH2MSGConvert tool](https://github.com/loadwordteam/SH2MSGConvert) and referencing the English EE `.mes` file for this text string. Learn how we handle this text string and you can then adjust this "by hand" for the various Russian translation packs: [stage_x_heaven_msg_e.zip](https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/files/11250937/stage_x_heaven_msg_e.zip)

**Comment by HellbringerOnline** [comment]
> ^ Typically, modified language pack font sheets chop off the Japanese characters to save on file size/performance. We actually warn about this on our project site for language packs that used modified font sheets:

I can take and overlay the Russian file on top of the original one and it should work, am I right? What utility can I edit the file so that it is read by the game?

> The way the game displays this portion of text is dumb/weird. I recommend using the [SH2MSGConvert tool](https://github.com/loadwordteam/SH2MSGConvert) and referencing the English EE `.mes` file for this text string. Learn how we handle this text string and you can then adjust this "by hand" for the various Russian translation packs: [stage_x_heaven_msg_e.zip](https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/files/11250937/stage_x_heaven_msg_e.zip)

Perhaps the `.mes` contains bytes to offset in addition to text. I used this utility but I'm not sure that I processed these files through it. I'll try this, thanks.

**Comment by Polymega** [comment]
> I can take and overlay the Russian file on top of the original one and it should work, am I right? What utility can I edit the file so that it is read by the game?

Yes, you could do that. While it would allow a user to switch to the Japanese language, all other Latin languages would still be affected by the replaced Russian characters. So I personally would recommend to keep the font sheet small as you have it (to save on file size/performance).

You can edit the file in Photoshop or GIMP. Note our project now supports PNG for the font sheet, so you could convert the Russian TGA font sheet to PNG now.

> Perhaps the .mes contains bytes to offset in addition to text. I used this utility but I'm not sure that I processed these files through it. I'll try this, thanks.

It might. It's been so long since I've messed with this particular text string I can't remember. All I remember is that the way the game handles this is really strange and I had to come up with a "hacky" solution to make it display correctly.

**Comment by HellbringerOnline** [comment]
> It might. It's been so long since I've messed with this particular text string I can't remember. All I remember is that the way the game handles this is really strange and I had to come up with a "hacky" solution to make it display correctly.

Thanks for the tips! I'll try to fix it

**Comment by 60d74** [comment]
а исправления планируются?

**Comment by HellbringerOnline** [comment]
@mikeoxmaull 
На данный момент без понятия как исправить, пытался менять разные значения байт файла перевода, не имеющих отношения к тексту, но это ничего не даёт либо полностью ломает текст. Возможно @Polymega когда-то сможет помочь.
At the moment I have no idea how to fix it, I tried to change different values of bytes of the translation file, but it does nothing or completely breaks the text. Maybe @Polymega will be able to help sometime.

**Comment by 60d74** [comment]
> @mikeoxmaull 
> 
> На данный момент без понятия как исправить, пытался менять разные значения байт файла перевода, не имеющих отношения к тексту, но это ничего не даёт либо полностью ломает текст. Возможно @Polymega когда-то сможет помочь.
> 
> At the moment I have no idea how to fix it, I tried to change different values of bytes of the translation file, but it does nothing or completely breaks the text. Maybe @Polymega will be able to help sometime.

ладно, но все равно спасибо, прошел всю игру с вашей адаптацией, больше проблем не наблюдал

**Comment by Polymega** [comment]
Is this still the problem you're facing?
https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/issues/8#issuecomment-1508496322

**Comment by HellbringerOnline** [comment]
> Is this still the problem you're facing? [#8 (comment)](https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/issues/8#issuecomment-1508496322)

Sorry, but I didn’t receive a notification that you responded. Yes, the problem is still relevant for today.

**Comment by Polymega** [comment]
No worries. I'd like to host a Russian translation pack on our project page ([see here](https://enhanced.townofsilenthill.com/SH2/languagepacks.htm)). Would you be interested in this also? If so, I'd like to work with you here to make sure everything is compliant for use with our project. If you would be interested, please select which Russian pack you'd like to be used for hosting on the project website, and I can then assist you with any cleanup for the pack (including that issue we're talking about here).

**Comment by HellbringerOnline** [comment]
> No worries. I'd like to host a Russian translation pack on our project page ([see here](https://enhanced.townofsilenthill.com/SH2/languagepacks.htm)). Would you be interested in this also? If so, I'd like to work with you here to make sure everything is compliant for use with our project. If you would be interested, please select which Russian pack you'd like to be used for hosting on the project website, and I can then assist you with any cleanup for the pack (including that issue we're talking about here).

Yes, I'm interested, I'm ready to discuss the details. If I had to choose only one pack, I would choose the pack by Metallist.

**Comment by Polymega** [comment]
Great! To start, please share with me the Metallist version of the language pack and I'll look it over and we can start discussion from there. If you prefer, we can continue discussion in this ticket or make a new ticket within your repo.

Thanks

**Comment by HellbringerOnline** [comment]
> Great! To start, please share with me the Metallist version of the language pack and I'll look it over and we can start discussion from there. If you prefer, we can continue discussion in this ticket or make a new ticket within your repo.
> 
> Thanks

You can get a translation from Metalist by simply downloading my repository, it is located in the "Silent Hill 2 by Metallist" folder:

https://github.com/HellbringerOnline/Silent-Hill-2-Enchanced-Edition-Rus/tree/master/Silent%20Hill%202%20by%20Metallist

**Comment by HellbringerOnline** [comment]
Вероятно решено здесь
https://github.com/ilyuXer/Silent-Hill-2-Enchanced-Edition-Rus
